export const NEWS_LIST_REQUEST = "NEWS_LIST_REQUEST";
export const NEWS_LIST_SUCCESS = "NEWS_LIST_SUCCESS";
export const NEWS_LIST_FAIL = "NEWS_LIST_FAIL";

export const NEWS_DETAILS_REQUEST = "NEWS_DETAILS_REQUEST";
export const NEWS_DETAILS_SUCCESS = "NEWS_DETAILS_SUCCESS";
export const NEWS_DETAILS_FAIL = "NEWS_DETAILS_FAIL";

export const NEWS_LATEST_REQUEST = "NEWS_LATEST_REQUEST";
export const NEWS_LATEST_SUCCESS = "NEWS_LATEST_SUCCESS";
export const NEWS_LATEST_FAIL = "NEWS_LATEST_FAIL";

export const NEWS_RELATED_REQUEST = "NEWS_RELATED_REQUEST";
export const NEWS_RELATED_SUCCESS = "NEWS_RELATED_SUCCESS";
export const NEWS_RELATED_FAIL = "NEWS_RELATED_FAIL";

export const NEWS_NOT_RELATED_REQUEST = "NEWS_NOT_RELATED_REQUEST";
export const NEWS_NOT_RELATED_SUCCESS = "NEWS_NOT_RELATED_SUCCESS";
export const NEWS_NOT_RELATED_FAIL = "NEWS_NOT_RELATED_FAIL";

export const NEWS_WRITE_REQUEST = "NEWS_WRITE_REQUEST";
export const NEWS_WRITE_SUCCESS = "NEWS_WRITE_SUCCESS";
export const NEWS_WRITE_FAIL = "NEWS_WRITE_FAIL";
export const NEWS_WRITE_RESET = "NEWS_WRITE_RESET";

export const NEWS_UPDATE_REQUEST = "NEWS_UPDATE_REQUEST";
export const NEWS_UPDATE_SUCCESS = "NEWS_UPDATE_SUCCESS";
export const NEWS_UPDATE_FAIL = "NEWS_UPDATE_FAIL";
export const NEWS_UPDATE_RESET = "NEWS_UPDATE_RESET";

export const NEWS_DELETE_REQUEST = "NEWS_DELETE_REQUEST";
export const NEWS_DELETE_SUCCESS = "NEWS_DELETE_SUCCESS";
export const NEWS_DELETE_FAIL = "NEWS_DELETE_FAIL";
export const NEWS_DELETE_RESET = "NEWS_DELETE_RESET";

export const NEWS_CATEGORY_LIST_REQUEST = "NEWS_CATEGORY_LIST_REQUEST";
export const NEWS_CATEGORY_LIST_SUCCESS = "NEWS_CATEGORY_LIST_SUCCESS";
export const NEWS_CATEGORY_LIST_FAIL = "NEWS_CATEGORY_LIST_FAIL";

export const NEWS_WRITE_COMMENT_REQUEST = "NEWS_WRITE_COMMENT_REQUEST";
export const NEWS_WRITE_COMMENT_SUCCESS = "NEWS_WRITE_COMMENT_SUCCESS";
export const NEWS_WRITE_COMMENT_FAIL = "NEWS_WRITE_COMMENT_FAIL";
export const NEWS_WRITE_COMMENT_RESET = "NEWS_WRITE_COMMENT_RESET";

export const NEWS_CATEGORY_REQUEST = "NEWS_CATEGORY_REQUEST";
export const NEWS_CATEGORY_SUCCESS = "NEWS_CATEGORY_SUCCESS";
export const NEWS_CATEGORY_FAIL = "NEWS_CATEGORY_FAIL";
